FROM maven:3.8.5-openjdk-17 AS build
COPY ..
RUN mvn clean package -DiskipTests

FROM openjdk:17.0.1-jdk-slim
COPY --FROM=BUILD /target/persistentinsights-1.0.0.jar app.jar
EXPOSE 8080
ENTRYPOINT["java","-jar","app.jar"]
